toggl_key : "XXXXXXX" # Can be found on https://www.toggl.com/user/edit
jira_url  : "http://jira.yourdomain.com"
jira_user : "USER"
# jira_pass : "PASS" # This property can be omitted and the script will try to read it from system keychain
start_time : # Leave blank to start from 00:00:00 today. Or specify a time in iso8601 format. A sample: "2012-05-15T03:00:00-04:00". Or put an integer here means "start from X days ago"
end_time : # Leave blank for all entries up to now

# Properties used by jira_issue_to_toggl_project.rb
jira_api_version : "latest"
toggl_workspace_id : "123456"
jira_sync_jql : 'project = YOURPROJECT'
