toggl_key : "XXXXXXX"
jira_url  : "http://jira.freewheel.tv"
jira_user : "USER"
jira_pass : "PASS"
start_time : # leave blank to start from 00:00:00 today, the format is iso8601, a sample is "2010-02-12T15:35:47+02:00"
end_time : # leave blank for all entries up to now
